export const httpErrorMessages = {
  400: 'Bad Request - The request not valid',
  401: 'Unauthorized - The request requires user authentication',
  403: 'Forbidden - The server understood the request, but is refusing to fulfill it',
  404: 'Not Found - The requested resource could not be found',
  405: 'Method Not Allowed - The request method is not supported for the requested resource',
  406: 'Not Acceptable - The requested resource is capable of generating only content',
  407: 'Proxy Authentication Required - The client must first authenticate itself with the proxy',
  408: 'Request Timeout - The server timed out waiting for the request',
  409: 'Conflict - The request could not be completed because of a conflict',
  410: 'Gone - The requested resource is no longer available',
  411: 'Length Required - The request did not specify the length of its content',
  412: 'Precondition Failed - The server does not meet one of the preconditions that the requester put on the request',
  413: 'Payload Too Large - The request is larger than the server is willing or able to process',
  414: 'URI Too Long - The URI provided was too long for the server to process',
  415: 'Unsupported Media Type - The request entity has a media type which the server or resource does not support',
  416: 'Range Not Satisfiable - The client has asked for a portion of the file, but the server cannot supply that portion',
  417: 'Expectation Failed - The server cannot meet the requirements of the Expect request-header field',
  418: "I'm a teapot - The server refuses the attempt to brew coffee with a teapot",
  421: 'Misdirected Request - The request was directed at a server that is not able to produce a response',
  422: 'Unprocessable Entity - The request was well-formed but was unable to be followed due to semantic errors',
  423: 'Locked - The resource that is being accessed is locked',
  424: 'Failed Dependency - The request failed due to failure of a previous request',
  426: 'Upgrade Required - The client should switch to a different protocol',
  428: 'Precondition Required - The origin server requires the request to be conditional',
  429: 'Too Many Requests - The user has sent too many requests in a given amount of time',
  431: 'Request Header Fields Too Large - The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large',
  451: 'Unavailable For Legal Reasons - The resource is unavailable due to legal reasons',
  500: 'Internal Server Error - The server has encountered a situation it does not know how to handle',
  501: 'Not Implemented - The request method is not supported by the server and cannot be handled',
  502: 'Bad Gateway - The server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed',
  503: 'Service Unavailable - The server is not ready to handle the request',
  504: 'Gateway Timeout - The server, while acting as a gateway or proxy, did not receive a timely response from an upstream server',
}
